### PR TITLE
Move meshzoo to test requirements

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by nschloe** [comment]
I'm not sure how `tests_require` works with `pytest` (which voropy uses as a test framework). Another possibility would be to add a file `test_requirements.txt` and pip-install that in the unit tests. That would work for now. Would you be okay with me adding this in another PR?

**Comment by nschloe** [comment]
I did just that now, version 0.5.1 released.

**Comment by ghisvail** [comment]
> I'm not sure how tests_require works with pytest (which voropy uses as a test framework).

The most common setups I found were either using `tests_require` + `pytest-runner`, which gives you a `python setup.py test` command to launch the tests, using `extras_require={'test': ['pytest', ...]}`, or just putting the test requirement in a `requirements-dev.txt` file. Your call.

**Comment by nschloe** [comment]
I've put it in `test-requirements.txt` now, integration tests are using it too.

**Pull request closed without merging**
